---
# yamllint disable rule:line-length
name: Actions Gos
on: 
  push:
    branches:
     - main
     - test_branch
  workflow_dispatch:
jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: RohitSaini04/github_action@main
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

